### ISSUE TITLE
黑色框一直存在

### ISSUE THREAD

**Issue by ssyy925** [yutianqaq/CSx4Ldr#1]
![x4Ldr](https://github.com/yutianqaq/CSx4Ldr/assets/157858119/83d9b3f7-50bc-4714-b72d-4a7199dfd3eb)

**Comment by ssyy925** [comment]
![x4Ldr-win](https://github.com/yutianqaq/CSx4Ldr/assets/157858119/03ce6048-0d8b-4baa-8e4d-404b1db10ea2)
微软自带的杀软，已经识别了

**Comment by yutianqaq** [comment]
黑框存在是预期行为。关于绕过 WD 过几天更新

**Comment by ssyy925** [comment]
感谢回复，加油！
